[2023-03-16T23:48:38.490+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: first_python_dag.first_python_task manual__2023-03-16T23:48:37.381648+00:00 [queued]>
[2023-03-16T23:48:38.502+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: first_python_dag.first_python_task manual__2023-03-16T23:48:37.381648+00:00 [queued]>
[2023-03-16T23:48:38.502+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T23:48:38.503+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-03-16T23:48:38.504+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-16T23:48:38.523+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): first_python_task> on 2023-03-16 23:48:37.381648+00:00
[2023-03-16T23:48:38.530+0000] {standard_task_runner.py:55} INFO - Started process 15333 to run task
[2023-03-16T23:48:38.539+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'first_python_dag', 'first_python_task', 'manual__2023-03-16T23:48:37.381648+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/second.py', '--cfg-path', '/tmp/tmpmzse4jg6']
[2023-03-16T23:48:38.540+0000] {standard_task_runner.py:83} INFO - Job 19: Subtask first_python_task
[2023-03-16T23:48:38.610+0000] {task_command.py:388} INFO - Running <TaskInstance: first_python_dag.first_python_task manual__2023-03-16T23:48:37.381648+00:00 [running]> on host e831dd1240d3
[2023-03-16T23:48:38.680+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=first_python_dag
AIRFLOW_CTX_TASK_ID=first_python_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-16T23:48:37.381648+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-16T23:48:37.381648+00:00
[2023-03-16T23:48:38.682+0000] {logging_mixin.py:137} INFO - Hello I am a Python function called by ***
[2023-03-16T23:48:38.682+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-16T23:48:38.691+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=first_python_dag, task_id=first_python_task, execution_date=20230316T234837, start_date=20230316T234838, end_date=20230316T234838
[2023-03-16T23:48:38.711+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-16T23:48:38.729+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
